version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"


  cockroachdb:
    image: cockroachdb/cockroach:v22.1.1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    environment:
      SPRING_DATASOURCE_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network

#  spring-boot-app:
#    image: your-spring-boot-image:latest
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://cockroachdb:26257/${SPRING_DATASOURCE_DATABASE}?sslmode=disable
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#    depends_on:
#      - cockroachdb
#    networks:
#      - app-network